linters:
  enable:
    - gosec
    - godot
    - misspell
    - stylecheck

linters-settings:
  stylecheck:
    go: "1.19"
    checks: ["all", "ST1*"]
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS"]

issues:
  exclude-use-default: false

output:
  format: colored-line-number

  #print lines of code with issues, default is true
  print-issued-lines: false

  #print linter name in the end of issue text, default is true
  print-linter-name: true
